manifest:
  version: "0.12"
  remotes:
    # Home Smart Mesh GitHub organization.
    - name: hsm
      url-base: https://github.com/HomeSmartMesh
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  defaults:
    remote: hsm

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v2.3.0
      path: nrf
    - name: nrfxlib
      remote: ncs
      repo-path: sdk-nrfxlib
      path: nrfxlib
      revision: v2.3.0
    - name: zephyr
      remote: ncs
      repo-path: sdk-zephyr
      revision: v3.2.99-ncs2
      import:
        name-allowlist:
          - cmsis
          - edtt
          - fatfs
          - hal_nordic
          - libmetal
          - littlefs
          - lvgl
          - mipi-sys-t
          - net-tools
          - nrf_hw_models
          - open-amp
          - openthread
          - segger
          - tinycrypt
    - name: openthread
      remote: ncs
      repo-path: sdk-openthread
      path: modules/lib/openthread
      revision: 2060039bbfec52ac00f22a7cc3213c2ab1df138e
    - name: mcuboot
      remote: ncs
      repo-path: sdk-mcuboot
      revision: v1.9.99-ncs4
      path: bootloader/mcuboot
    - name: mbedtls
      remote: ncs
      path: modules/crypto/mbedtls
      repo-path: sdk-mbedtls
      revision: v3.1.0-ncs3

  self:
    path: hsm
    west-commands: nrf/scripts/west-commands.yml
